server:
  port: 8888

logging:
  level:
    org.springframework.cloud: 'DEBUG'


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.comcast.com/esp/esp-properties.git
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI_PASSWORD}
          searchPaths: "*"
          repos:
            team-t:
              pattern: team-t*
              uri: https://github.comcast.com/esp/team-t-properties.git
              username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI_USERNAME}
              password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI_PASSWORD}
              searchPaths: "*"


security:
  basic:
    enabled: true
  user:
    name: config_client
    password: ${esp.config.server.password}

management:
  security:
    enabled: false